version: "3.9"

networks:
  traefik-network: {}
  user-auth: {}

services:

  reverse-proxy:
    image: traefik:v2.4
    #build: ./traefik
    container_name: traefik
    command:
      #- --log.level=DEBUG
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      #HTTP to HTTPS redirect
#      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
#      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
#      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
#      - "--certificatesresolvers.myresolver.acme.email=wi19002@lehre.dhbw-stuttgart.de"
#      - "--certificatesresolvers.myresolver.acme.storage=/cert/acme.json"
    ports:
      - "80:80"
      - "443:443"
      #ebabled die Browser Oberfläche zusammen mit api insecure= true
      - "8080:8080"
    volumes:
      #Volumes are necessary for the nodemon integration -> no rebuilding necessary
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      #necessary for Let#s encrypt
#      - "./traefik/letsencrypt:/letsencrypt/"
    networks:
      - traefik-network
    labels:
#      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
#      - "traefik.http.routers.http-catchall.entrypoints=web"
#      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.docker.network=traefik-network"


  user_events:
    build: ./user_events
    container_name: user-events
    labels:
      #enable container in traefik
      - "traefik.enable=true"
      #route definition
      - "traefik.http.routers.user_events.rule=Host(`tester.localhost`)"
      #http redirect
#      - "traefik.http.routers.user_events.entrypoints=websecure"
#      - "traefik.http.routers.user_events.tls=true"
#      - "traefik.http.routers.user_events.tls.certresolver=myresolver"
    volumes:
      - ./user_events:/app
    networks:
      - traefik-network


  user_db:
    image: mongo:latest
    container_name: user_db
    networks:
      - user-auth

  user_logins:
    build: ./user_logins
    container_name: user-logins
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user_logins.rule=Host(`test.localhost`)"
      #http redirect
#      - "traefik.http.routers.user_logins.entrypoints=websecure"
#      - "traefik.http.routers.user_login.tls=true"
#      - "traefik.http.routers.user_logins.tls.certresolver=myresolver"
    volumes:
      - ./user_logins:/app
    networks:
      - user-auth
      - traefik-network