version: "3.9"

networks:
  traefik-network: {}
  user-auth: {}
  user-events: {}

services:

  reverse-proxy:
    #image: traefik:v2.4
    build: ./traefik
    container_name: traefik
    command:
      #- --log.level=DEBUG
      #    - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--configFile=./etc/traefik/traefik.yml"
    ports:
      #    - "80:80"
      - "443:443"
      #enabled die Browser Oberfläche zusammen mit api insecure= true
  #    - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/configuration:/etc/traefik/dynamic/certs-traefik.yaml"
      - "./traefik/configuration/certificates:/etc/certs/"
    networks:
      - traefik-network
    labels:
      - "traefik.docker.network=traefik-network"


  user_db:
    image: mongo:latest
    container_name: user_db
    networks:
      - user-auth

  user_events_db:
    image: mongo:latest
    container_name: user_events_db
    networks:
      - user-events

  user_logins:
    build: ./user_logins
    container_name: user-logins
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user_logins.rule=Host(`www.itworksonmymachine.studio`) && Path(`/register`) || Path(`/login`) || Path(`/getUser`)"
      - "traefik.http.routers.user_logins.entrypoints=websecure"
      - "traefik.http.routers.user_logins.tls=true"
    volumes:
      - ./user_logins:/app
    networks:
      - traefik-network
      - user-auth

  user_events:
    build: ./user_events
    container_name: user-events
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user_events.rule=Host(`www.itworksonmymachine.studio`) && Path(`/events`) || Path(`/medications`) || Path(`/files`) || Path(`/folders`) || Path(`/downloads`)"
      - "traefik.http.routers.user_events.entrypoints=websecure"
      - "traefik.http.routers.user_events.tls=true"

    volumes:
      - ./user_events:/app
    networks:
      - traefik-network
      - user-events