version: "3.9"

networks:
  traefik-network: {}
  user-auth: {}



services:

  reverse-proxy:
    image: traefik:v2.4
    container_name: traefik
    command:
      #- --log.level=DEBUG
      - --entrypoints.web.address=:80
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
      #ebabled die Browser Oberfläche zusammen mit api insecure= true
      #- "8080:8080"
    volumes:
      #Volumes are necessary for the nodemon integration -> no rebuilding necessary
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-network


  user_events:
    build: ./user_events
    container_name: user-events
    labels:
      - traefik.enable=true
      - traefik.http.routers.user_events.rule=Host(`test.localhost`)
    volumes:
      - ./user_events:/app
    networks:
      - traefik-network


  user_db:
    image: mongo:latest
    container_name: user_db
    labels:
      - traefik.enable=true
      - traefik.http.routers.user_events.rule=Host(`test2.localhost`)
    networks:
      - user-auth

  user_logins:
    build: ./user_logins
    container_name: user-logins
    labels:
      - traefik.enable=true
      - traefik.http.routers.user_events.rule=Host(`test3.localhost`)
    volumes:
      - ./user_logins:/app
    networks:
      - user-auth
      - traefik-network